# Site settings
title: ChessWu个人博客
email: 249534284@qq.com
description: Person Blog,Save Study Data,Show Myself
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://chessjava.gitee.io/studydata" # the base hostname & protocol for your site
copyright: '&copy; 2019-Now ChessWu个人博客'

# Build settings
markdown: kramdown

# Custom theme could be generated at: https://getmdl.io/customize/index.html
material_theme: blue-deep_orange

# Google Analytics account ID (UA-XXXXXXXX-X)

google-analytics-ua: 
